### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by undcloud** [camenduru/CoDeF-colab#3]
Traceback (most recent call last):
  File "/content/CoDeF/train.py", line 556, in <module>
    hparams = get_opts()
  File "/content/CoDeF/opt.py", line 157, in get_opts
    with open(args.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/test/base.yaml'

**Comment by undcloud** [comment]
# @title Generate Video (Step 3)

GPUS=0
NAME="scene_0"
EXP_NAME="base"
ROOT_DIRECTORY=f"ckpts/all_sequences/{NAME}/{NAME}"
LOG_SAVE_PATH=f"logs/test_all_sequences/{NAME}"
MASK_DIRECTORY=f"ckpts/all_sequences/{NAME}/{NAME}_masks_0 ckpts/all_sequences/{NAME}/{NAME}_masks_1"
CONFIG_DIRECTORY=f"configs/{NAME}/{EXP_NAME}.yaml"
CANONICAL_DIR=f"ckpts/all_sequences/{NAME}/{EXP_NAME}_control"
WEIGHT_PATH= f"ckpts/{NAME}.ckpt" 

!python train.py --test --encode_w \
                --root_dir $ROOT_DIRECTORY \
                --log_save_path $LOG_SAVE_PATH \
                --mask_dir $MASK_DIRECTORY \
                --weight_path $WEIGHT_PATH \
                --gpus $GPUS \
                --canonical_dir $CANONICAL_DIR \
                --config $CONFIG_DIRECTORY \
                --exp_name $EXP_NAME
