### ISSUE TITLE
directory not found 

### ISSUE THREAD

**Issue by sergedahdouh** [camenduru/CoDeF-colab#4]
hello, 
I am receiving the following error 

Traceback (most recent call last):
  File "/content/CoDeF/train.py", line 556, in <module>
    hparams = get_opts()
  File "/content/CoDeF/opt.py", line 157, in get_opts
    with open(args.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/serge/base.yaml'

<img width="1435" alt="Screenshot 2023-08-27 at 00 37 19" src="https://github.com/camenduru/CoDeF-colab/assets/40029858/5876e55e-3164-40d8-b43a-ec58a8f38d44">

**Comment by LabMember01** [comment]
Means you haven't created a config file for your project "configs/serge/base.yaml"
